openapi: 3.0.3
info:
  title: Conduit API
  description: Conduit API
  contact:
    name: RealWorld
    url: https://realworld.io
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
  - url: /api
paths:
  /iam/auth:
    $ref: 'iam/auth.yml#'
  /iam/user/me:
    $ref: 'iam/user.me.yml#'
  # /iam/user/{id}:
  #   $ref: 'iam/user.id.yml#'
  # /iam/user:
  #   $ref: 'iam/user.yml#'
  /profile:
    $ref: 'blog/profile.yml#'
  /profile/{id}:
    $ref: 'blog/profile.id.yml#'
  /profile/follow:
    $ref: 'blog/profile.follow.yml#'
  /profile/follow/{id}:
    $ref: 'blog/profile.follow.id.yml#'
  /article:
    $ref: 'blog/article.yml#'
  /article/{id}:
    $ref: 'blog/article.id.yml#'
  /article/{id}/tags:
    $ref: 'blog/article.id.tags.yml#'
  /article/{id}/version:
    $ref: 'blog/article.id.version.yml#'
  /article/{id}/version/{version_id}:
    $ref: 'blog/article.id.version.id.yml#'
