openapi: 3.0.3
info:
  title: Conduit API
  description: Conduit API
  contact:
    name: RealWorld
    url: https://realworld.io
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
  - url: /api
paths:
  /iam/auth:
    $ref: 'iam/auth.yml#'
  /iam/user/me:
    $ref: 'iam/user.me.yml#'
  # /iam/user/{id}:
  #   $ref: 'iam/user.id.yml#'
  # /iam/user:
  #   $ref: 'iam/user.yml#'
  /profile:
    $ref: 'blog/profile.operation.yml#/profile'
  /profile/{id}:
    $ref: 'blog/profile.operation.yml#/profile_id'
  /profile/follow:
    $ref: 'blog/profile.operation.yml#/profile_follow'
  /profile/follow/{id}:
    $ref: 'blog/profile.operation.yml#/profile_follow_id'
  /article:
    $ref: 'blog/article.operation.yml#/article'
  /article/{id}:
    $ref: 'blog/article.operation.yml#/article_id'
  /article/{id}/tags:
    $ref: 'blog/article.operation.yml#/article_id_tags'
  /article/{id}/version:
    $ref: 'blog/article.operation.yml#/article_id_version'
  /article/{id}/version/{version_id}:
    $ref: 'blog/article.operation.yml#/article_id_version_id'
