openapi: 3.0.3
info:
  title: Conduit API
  description: Conduit Modified API
  contact:
    name: RealWorld
    url: https://realworld.io
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
  - url: /api
# TODO: improve error responses
# - Unauthorized
# - Forbidden
# - Conflict
# - Internal server error
# - Service unavailable
# TODO: add cache control headers (ETag, Last-Modified, Cache-Control)
paths:
  /iam/auth:
    $ref: 'iam/auth.yml#'
  # /iam/user:
  #   $ref: 'iam/user.operation.yml#/user'
  /iam/user/me:
    $ref: 'iam/user.operation.yml#/user_me'
  /iam/user/{id}:
    $ref: 'iam/user.operation.yml#/user_id'
  # /iam/user/{id}/change_password:
  #   $ref: 'iam/user.operation.yml#/user_id_change_password'
  # /iam/user/{id}/send_email_change:
  #   $ref: 'iam/user.operation.yml#/user_id_send_email_change'
  # /iam/user/{id}/change_email:
  #   $ref: 'iam/user.operation.yml#/user_id_change_email'
  # /iam/user/send_password_reset:
  #   $ref: 'iam/user.operation.yml#/user_send_password_reset'
  # /iam/user/reset_password:
  #   $ref: 'iam/user.operation.yml#/user_reset_password'
  /profile:
    $ref: 'blog/profile.operation.yml#/profile'
  /profile/{id}:
    $ref: 'blog/profile.operation.yml#/profile_id'
  /profile/follow:
    $ref: 'blog/profile.operation.yml#/profile_follow'
  /profile/follow/{id}:
    $ref: 'blog/profile.operation.yml#/profile_follow_id'
  /article:
    $ref: 'blog/article.operation.yml#/article'
  /article/{id}:
    $ref: 'blog/article.operation.yml#/article_id'
  /article/{id}/tags:
    $ref: 'blog/article.operation.yml#/article_id_tags'
  /article/{id}/version:
    $ref: 'blog/article.operation.yml#/article_id_version'
  /article/{id}/version/{version_id}:
    $ref: 'blog/article.operation.yml#/article_id_version_id'
  /article/favorite:
    $ref: 'blog/favorite.operation.yml#/favorite'
  /article/favorite/{id}:
    $ref: 'blog/favorite.operation.yml#/favorite_id'
  /article/comment:
    $ref: 'blog/comment.operation.yml#/comment'
  /article/comment/{id}:
    $ref: 'blog/comment.operation.yml#/comment_id'
  /article/comment/vote:
    $ref: 'blog/vote.operation.yml#/vote'
  /article/comment/vote/{id}:
    $ref: 'blog/vote.operation.yml#/vote_id'

components:
  securitySchemes:
    UserAuthentication:
      $ref: 'component/security.yml#/UserAuthentication'
    ResetUserPasswordAuthorization:
      $ref: 'component/security.yml#/ResetUserPasswordAuthorization'
    ChangeUserEmailAuthorization:
      $ref: 'component/security.yml#/ChangeUserEmailAuthorization'
