AnyType:
  description: Can be any value - string, number, boolean, array or object.
  anyOf:
  - type: string
  - type: number
  - type: integer
  - type: boolean
  - type: array
    items: {}
  - type: object
  nullable: true

OffsetPagination:
  type: object
  properties:
    data:
      type: array
      items:
        type: object
    offset:
      type: integer
      format: int32
      description: number of items skiped in the query
    limit:
      type: integer
      format: int32
      description: maximum count of items returned in the query
    next:
      type: integer
      format: int32
      nullable: true
      description: offset the request should use to query the next items
    previous:
      type: integer
      format: int32
      nullable: true
      description: offset the request should use to query the previous items
    count:
      type: integer
      format: int32
      description: number of items in the response
    total:
      type: integer
      format: int32
      description: total number of items for the query
  required:
  - offset
  - limit
  - next
  - previous
  - count
  - total
  - data

# TODO: remove
Profile:
  required:
    - bio
    - following
    - image
    - username
  type: object
  properties:
    username:
      type: string
    bio:
      type: string
    image:
      type: string
    following:
      type: boolean
Article:
  required:
    - author
    - body
    - description
    - favorited
    - favorite_count
    - slug
    - tag_list
    - title
    - created
    - updated
  type: object
  properties:
    slug:
      type: string
    title:
      type: string
    description:
      type: string
    body:
      type: string
    tag_list:
      type: array
      items:
        type: string
    favorited:
      type: boolean
    favorite_count:
      type: integer
    author:
      $ref: '#/Profile'
    created:
      type: string
      format: date-time
    updated:
      type: string
      format: date-time
PutArticle:
  required:
    - title
    - description
    - body
    - tag_list
  type: object
  properties:
    title:
      type: string
    description:
      type: string
    body:
      type: string
    tag_list:
      type: array
      items:
        type: string
Comment:
  required:
    - author
    - body
    - createdAt
    - id
    - updatedAt
  type: object
  properties:
    id:
      type: integer
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
    body:
      type: string
    author:
      $ref: '#/Profile'
SingleCommentResponse:
  required:
    - comment
  type: object
  properties:
    comment:
      $ref: '#/Comment'
MultipleCommentsResponse:
  required:
    - comments
  type: object
  properties:
    comments:
      type: array
      items:
        $ref: '#/Comment'
NewComment:
  required:
    - body
  type: object
  properties:
    body:
      type: string
NewCommentRequest:
  required:
    - comment
  type: object
  properties:
    comment:
      $ref: '#/NewComment'
TagsResponse:
  required:
    - tags
  type: object
  properties:
    tags:
      type: array
      items:
        type: string
Token:
  type: apiKey
  description: "For accessing the protected API resources, you must have received\
    \ a a valid JWT token after registering or logging in. This JWT token must\
    \ then be used for all protected resources by passing it in via the 'Authorization'\
    \ header.\n\nA JWT token is generated by the API by either registering via\
    \ /users or logging in via /users/login.\n\nThe following format must be in\
    \ the 'Authorization' header :\n\n    Token xxxxxx.yyyyyyy.zzzzzz\n    \n"
  name: Authorization
  in: header
