AnyType:
  description: Can be any value - string, number, boolean, array or object.
  anyOf:
  - type: string
  - type: number
  - type: integer
  - type: boolean
  - type: array
    items: {}
  - type: object
  nullable: true

OffsetPagination:
  type: object
  properties:
    data:
      type: array
      items:
        type: object
    offset:
      type: integer
      format: int32
      description: number of items skiped in the query
    limit:
      type: integer
      format: int32
      description: maximum count of items returned in the query
    next:
      type: integer
      format: int32
      nullable: true
      description: offset the request should use to query the next items
    previous:
      type: integer
      format: int32
      nullable: true
      description: offset the request should use to query the previous items
    count:
      type: integer
      format: int32
      description: number of items in the response
    total:
      type: integer
      format: int32
      description: total number of items for the query
  required:
  - offset
  - limit
  - next
  - previous
  - count
  - total
  - data

Version:
  type: integer
  format: int32
  minimum: 1

Resource:
  type: object
  properties:
    id:
      type: string
      format: uuid
    version:
      $ref: "#/Version"
    created:
      type: string
      format: date-time
    updated:
      type: string
      format: date-time
      nullable: true
  required:
  - id
  - version
  - created
  - updated
